# Generated by Django 2.2.1 on 2019-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('addr', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('foods', models.ManyToManyField(to='testapp.Food_Requested')),
            ],
        ),
    ]
