# Generated by Django 2.2.1 on 2019-05-04 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('county', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('zip_code', models.CharField(default='', max_length=5)),
                ('email', models.EmailField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=10)),
                ('website', models.CharField(default='', max_length=250)),
                ('start_Time', models.DateField(default=datetime.date.today)),
                ('close_Time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('street', models.CharField(default='', max_length=250)),
                ('county', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('zip_code', models.CharField(default='', max_length=5)),
                ('email', models.EmailField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=10)),
                ('website', models.CharField(default='', max_length=250)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('operation_days', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='food_requested',
            name='containsDairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='containsGluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='containsNuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='containsSeafood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='food_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='isPerishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='isVegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='isVegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='quantity_requested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='quantity_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='quantity_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_requested',
            name='requested_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_served', models.CharField(default='', max_length=255)),
                ('ethnicity_served', models.CharField(default='', max_length=255)),
                ('age_served', models.IntegerField(default=0)),
                ('requested_time', models.DateField(default=datetime.date.today)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Requester')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Foodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Requester')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Produced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('food_type', models.CharField(default='', max_length=250)),
                ('isPerishable', models.BooleanField(default=False)),
                ('isVegetarian', models.BooleanField(default=False)),
                ('isVegan', models.BooleanField(default=False)),
                ('containsDairy', models.BooleanField(default=False)),
                ('containsNuts', models.BooleanField(default=False)),
                ('containsSeafood', models.BooleanField(default=False)),
                ('containsGluten', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(default=datetime.date.today)),
                ('produced_date', models.DateField(default=datetime.date.today)),
                ('quantity_weight', models.IntegerField(default=0)),
                ('quantity_unit', models.IntegerField(default=0)),
                ('originator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Cater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_people_served', models.IntegerField(default=0)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Producer')),
            ],
        ),
        migrations.AddField(
            model_name='food_requested',
            name='originator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.Requester'),
        ),
    ]
